"""Initial migration

Revision ID: 268a42b26d3e
Revises: 
Create Date: 2023-04-13 19:21:15.177118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268a42b26d3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postcards')
    # ### end Alembic commands ###
